CREATE TABLE imovel (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietario   VARCHAR(120),
    municipio      VARCHAR(120),
    uf             VARCHAR(2),
    bairro         VARCHAR(100),
    rua            VARCHAR(150),
    numero         VARCHAR(10),
    latitude       NUMERIC(10,7),
    longitude      NUMERIC(10,7),
    area_m2        NUMERIC(12,2),
    ativo          BOOLEAN NOT NULL,
    criado_em      TIMESTAMPTZ,
    atualizado_em  TIMESTAMPTZ
)