CREATE TABLE proprietario(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE,
    criado_em      TIMESTAMPTZ,
    atualizado_em  TIMESTAMPTZ
);

-- Trazendo nomes que já existem em imóveis para a nova tabela de proprietario
INSERT INTO proprietario (nome)
SELECT DISTINCT proprietario FROM imovel;

ALTER TABLE imovel ADD COLUMN proprietario_id BIGINT REFERENCES proprietario (id);

UPDATE imovel i SET proprietario_id = p.id FROM proprietario p WHERE p.nome = i.proprietario;

ALTER TABLE imovel DROP COLUMN proprietario;